/**
 * Public API boundary for game.loop.
 *
 * Generated by scripts/architecture/generate-public-facades.mjs.
 * Exposes contracts and capability tokens only.
 * Concrete implementations are not part of this public facade.
 */
export * from "../../../contracts/game-loop/types";
export * from "../../../tokens/game-loop";
