/**
 * Public API boundary for game.world.
 *
 * Generated by scripts/architecture/generate-public-facades.mjs.
 * Exposes contracts and capability tokens only.
 * Concrete implementations are not part of this public facade.
 */
export * from "../../../contracts/world/types";
export * from "../../../tokens/world";
