/**
 * Public API boundary for game.vfx.
 *
 * Generated by scripts/architecture/generate-public-facades.mjs.
 * Exposes contracts and capability tokens only.
 * Concrete implementations are not part of this public facade.
 */
export * from "../../../contracts/vfx/types";
export * from "../../../tokens/vfx";
